### ISSUE TITLE
LightLink support

### ISSUE THREAD

**Issue by TheKillerremijn** [zigbeer/zigbee-shepherd#11]
Hello,

I was wondering if it was on the roadmap to implement LightLink, mainly the TouchLink part of the spec

This would allow zigbee-shepherd to control Hue Bulb and various other smart-lights

Thank you, 
- Nick Remijn

**Comment by splitice** [comment]
TouchLink requires that the current ZNP image be compiled with support with the propriety LL key (which you may be able to find via Google).

Getting everything to fit in the firmware is challenging. We have got an experimental build internally, but currently are not developing in that area (as we are happy enough to using ZHA compatible / LL certificed bulbs).

**Comment by jackchased** [comment]
Hi @TheKillerremijn,

zigbee-shepherd current firmware is [TI Home Automation](http://www.ti.com/tool/z-stack-archive) stack, but LightLink is another z-stack. We think it will be difficult to integrate LightLink and Home Automation firmware. If possible, maybe LightLink would be another new project. So it will not be implemented in zigbee-shepherd.
