### ISSUE TITLE
Removing an offline device

### ISSUE THREAD

**Issue by TheKillerremijn** [zigbeer/zigbee-shepherd#14]
Hello,

I am currently having trouble with removing devices
I need to be able to remove a device from the network, however, if the device is offline, this currently seems impossible

- Nick Remijn

**Comment by jackchased** [comment]
In order to ensure that the device is indeed removed from the network, so the device should be online.

**Comment by simenkid** [comment]
Hi @TheKillerremijn,

The shepherd is a generic controller which will throw an offine operational error to developers for API behavior consistency.

No one can "really" tell a remote device to leave the network when it is offline (maybe sleeping), thus the shepherd leaves this to developers to tackle by themselves (shpeherd doesn't know how developers like to deal with this situation).

For example, if you like, you can pend a request to tell a device to leave at the moment when it comes alive again. This will ensure the "leaving behavior" known by the developers.
