### ISSUE TITLE
how many devices i can mount 

### ISSUE THREAD

**Issue by amigomcu** [zigbeer/zigbee-shepherd#16]
hi all,
now , i have been mount my self app*1(custom device id,and cluster,att and cmds) on zigbee-shepherd.
how many devices i can mount ?

*1:
zApp is an instance created by the ZCL framework zive

**Comment by amigomcu** [comment]
hi all,
Mount *1 , i don't see the [zigbee-demo](https://github.com/zigbeer/zigbee-demo) mount the zApp.
what kind of state need mount? 

i mount self ZApp(HA Light profile) , the end device report attribute or send cmd.
the app show the Coord ind event attReport /device change,not sensor device ?

*1:
Mounts a zigbee application zApp that will be registered to the coordinator as a local endpoint

**Comment by jackchased** [comment]
Hi @amigomcu,

A zigbee device can have 240 endpoints, but the enpointId 1-10 are reserved for zigbee-shepherd. So the max endpoint can mount is 230.

If you want to implement the IAS CIE or any application like temperature, humidity sensor **on gateway**, you will need to mount the zApp.
