### ISSUE TITLE
Is it possible to send a proprietary command?

### ISSUE THREAD

**Issue by liyiwu777** [zigbeer/zigbee-shepherd#4]
Hi,

If I need to send a proprietary command (cId and zclData are defined by vendor), what API I could use?

Thanks.

**Comment by simenkid** [comment]
Hello @liyiwu777 ,

  zigbee-shepherd can handle the proprietary command but needs some customization. It encourages users follow the public standard, thus it doesn't export the functionality to support proprietary definitions (Too hard to consider the variety, and following the public standard is the best policy I think).

  Please contact the team: support@sivann.com.tw if you need some help with the proprietary things.

**Comment by liyiwu777** [comment]
I will ask for help. Many Thanks.
