### ISSUE TITLE
Can be used to replicate the Hue Bridge?

### ISSUE THREAD

**Issue by mariusmotea** [zigbeer/zigbee-shepherd#50]
Hi,

I have a project that emulate the hue bridge and can work with different types of lights and sensors. Currently i'm using deconz for zigbee communication but there are some issues with deconz and i want to try also other alternatives. I want to know if this can work with Philips, IKEA and Xiaomi zigbee lighs/sensors.

Thanks,
Marius.

**Comment by jackchased** [comment]
Hi @mariusmotea, you can refer to this project [**zigbee2mqtt**](https://github.com/Koenkk/zigbee2mqtt) and [**supported devices**](https://github.com/Koenkk/zigbee2mqtt/wiki/Supported-devices) list. Thanks!

**Comment by mariusmotea** [comment]
Thanks, seams soon i will be able to replace deconz with zigbee2mqtt as it will get support for tradfri devices.
