### ISSUE TITLE
zigbee-shepherd might be outdated. Please help!

### ISSUE THREAD

**Issue by anhkysu** [zigbeer/zigbee-shepherd#66]
Thank you very much for your dedication into this invaluable library. But as the image below goes, whether your library might not be updated yet or it's my mistake for some reasons, please give me a guide. We are working on a research project about Zigbee and this library really help us if it works.
![CaptureError](https://user-images.githubusercontent.com/46838325/84610900-6cd79400-aee6-11ea-8861-1ce1865b2934.PNG)

**Comment by simenkid** [comment]
Hi @anhkysu 
I suggest you refer to the next generation of zigbee-shepeherd: Koenkk's [zigbee-herdsman](https://github.com/Koenkk/zigbee-herdsman)

**Comment by anhkysu** [comment]
Thank you @simenkid! I will give it a try
