### ISSUE TITLE
Crash When pairing new device

### ISSUE THREAD

**Issue by TheKillerremijn** [zigbeer/zigbee-shepherd#7]
The Zigbee-Sheperd Library crashes when I attempt to connect a new Smarthings Sensor

Crash log

```
/opt/user/dev/node_modules/zigbee-shepherd/lib/components/controller.js:550
                self._joinQueue.shift()();
                                       ^

TypeError: self._joinQueue.shift(...) is not a function
    at Immediate._onImmediate (/opt/user/dev/node_modules/zigbee-shepherd/lib/components/controller.js:550:40)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

**Comment by jackchased** [comment]
Hi @TheKillerremijn,

Could you print the `console.log(self._joinQueue.shift())`  please?

**Comment by splitice** [comment]
Also could you let me know if https://github.com/HollyAssistTeam/zigbee-shepherd/commit/29c0f43e5373567d65499eb9fa9feda393d495ae helps?

We have seen it occasionally too and think its a race condition.

**Comment by TheKillerremijn** [comment]
Alrighty, Sorry for the late response, However, the last commit seems to have fixed my issue

Thank you!
